### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-sleeper

on: [push]

jobs:

  pytest:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.11
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      env:
        SAMPLE_CONFIG_LEAGUE_ID: ${{ secrets.SAMPLE_CONFIG_LEAGUE_ID }}
      run: |
        poetry run pytest --capture=no
